version: '3.1'

services:
  app:
    build: .
    container_name: api-forum
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
  # db:
  #   image: mariadb:10
  #   restart: always
  #   environment:
  #     - MARIADB_DATABASE=${DATABASE_NAME}
  #     - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
  #     - MARIADB_USER=${DATABASE_USER}
  #     - MARIADB_PORT=${DATABASE_PORT}
  #   ports:
  #     - ${DATABASE_PORT}:${DATABASE_PORT}
  admin:
    image: adminer
    ports:
      - ${DATABASE_ADMIN_PORT}:${DATABASE_ADMIN_PORT}
    depends_on:
      - db
