version: '3.0'

services:
  # app:
  #   build: .
  #   container_name: api-forum
  #   environment:
  #     - PORT=${PORT}
  #     - DATABASE_PORT=${DATABASE_PORT}
  #     - DATABASE_USER=${DATABASE_USER}
  #     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  #     - DATABASE_NAME=${DATABASE_NAME}
  #     - DATABASE_HOST=${DATABASE_HOST}
  #     - DATABASE_ADMIN_PORT=${DATABASE_ADMIN_PORT}
  #     - DATABASE_URL=${DATABASE_URL}
  #   ports:
  #     - ${PORT}:${PORT}
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/app/src
  #   networks:
  #     - default
  db:
    image: mariadb:10
    restart: always
    environment:
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PORT=${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - default
  admin:
    image: adminer
    ports:
      - ${DATABASE_ADMIN_PORT}:${DATABASE_ADMIN_PORT}
    depends_on:
      - db
    networks:
      - default
